name: Update npm Package

on:
  push:
    branches:
      - dev

jobs:
  update-package:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build package
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run build

      - name: Publish package
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm version patch
          npm publish --access public

      - name: Update package version
        run: |
          $version = npm view story-book-test-package-git version
          (Get-Content package.json) -replace '"version": ".*"', '"version": "'+$version+'"' | Set-Content package.json

      - name: Commit and push changes
        run: |
          git config user.name "Risini1998"
          git config user.email "risinipiyathma1998@gmal.com"
          git add package.json
          git commit -m "Update package version to $VERSION"
          git push

